---
title: "NFL RB Rushing Linear Regression Model"
author: "Ethan Xu"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Setup
require(tidyverse)
require(caret)
df <- read.csv("https://github.com/ethan-j-xu/nfl-rushing-model/raw/main/NFL%202022-2023%20Rushing%20Data%20-%20Sheet1.csv")
df <- df %>%
  filter(Postition == 'RB') %>%
  mutate(Player = gsub("[*+]", "", Player))
df
```

```{r}
suppressWarnings({ 
library(ranger)
rf_model <- ranger(Rushing.Yards ~ . - Rank - Player - School - Position -YPC - YPG, data = df, num.trees = 100, mtry = 5, importance = 'impurity')

variable_importance <- importance(rf_model)

sorted_importance <- sort(variable_importance, decreasing = TRUE)
par(mar = c(10, 10, 2, 2))
n_top_variables <- 10  # Adjust this to the number of top variables you want to display
top_variables <- head(sorted_importance, n_top_variables)
barplot(top_variables, main = "Top Variable Importance", xlab = "Importance Score", horiz = TRUE, las = 2)
})
```

```{r}
cor(df %>% select(Rushing.Attempts, First.Downs, Rushing.TDs, Games.Started, Rushing.Success.Rate, Longest.Rushing.Attempt))

yardsPrediction = lm (Rushing.Yards ~ Rushing.Attempts + Rushing.Success.Rate, data = df)
summary(yardsPrediction)

df %>%
  mutate(errors = Rushing.Yards - predict(yardsPrediction)) %>% # Create errors column for differences between actual and predicted future earnings 
  ggplot(aes(x = errors)) + #Plot our findings, and visualize how frequently our model was off by a certain amount.
  geom_histogram() +
  labs(x = 'Error Level',        # Label for x-axis
       y = 'Frequency of Errors Level',                # Label for y-axis
       title = 'Accuracy of Rushing Yards Prediction Model')  # Title for the plot

#Plots the predictions and residuals
residuals_df <- data.frame(Residuals = resid(yardsPrediction), Predicted = predict(yardsPrediction))

ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +  # Add a dashed line at y = 0
  labs(x = "Predicted Values", y = "Residuals") +
  ggtitle("Residual Plot")

df %>%
  mutate(errors = Rushing.Yards - predict(yardsPrediction)) %>% # Create errors column for differences between actual and predicted future earnings 
  ggplot(aes(x = Rushing.Attempts, y = errors)) + #Plot our findings, and visualize how accurate our model was for each level of rushing attempts
  geom_point() +
  geom_smooth() + #Add line of best fit
  labs(x = 'Rushing.Attempts',        # Label for x-axis
       y = 'Error Level',                # Label for y-axis
       title = 'Accuracy of Rushings Yards Prediction Model by Rushing.Attempts')

df %>%
  mutate(errors = Rushing.Yards - predict(yardsPrediction)) %>% # Create errors column for differences between actual and predicted future earnings 
  ggplot(aes(x = Rushing.Success.Rate, y = errors)) + #Plot our findings, and visualize how accurate our model was for each level of rushing success
  geom_point() +
  geom_smooth() + #Add line of best fit
  labs(x = 'Rushing.Success.Rate',        # Label for x-axis
       y = 'Error Level',                # Label for y-axis
       title = 'Accuracy of Rushings Yards Prediction Model by Rushing.Success.Rate')
```

```{r}
library(caret)
set.seed(123) # For reproducibility

cv_results <- train(y = df$Rushing.Yards, x = df[, c("Rushing.Attempts", "Rushing.Success.Rate")], method = "lm", trControl = trainControl(method = "cv", number = 50))
print(cv_results)
```

```{r}
df %>%
  mutate(errors = Rushing.Yards - predict(yardsPrediction)) %>%
  mutate(sq_error = errors^2) %>% # Calculate the squared errors
  summarise(mean_sq = mean(sq_error)) %>% # Calculate the mean squared errors
  mutate(sq_of_the_mean_sq = sqrt(mean_sq))

#RMSE 100-fold CV
set.seed(123)
cvRes <- NULL # Instantiate an empty object to store data from the loop
for(i in 1:100) { # Loop 100 times
  inds <- sample(x = 1:nrow(df), # Sample from the row numbers of the movies_analysis dataframe
                 size = round(nrow(df)*0.8), # Set the size to be 80% of the total rows (don't forget to round()!)
                 replace = FALSE) # Sample WITHOUT replacement
  
  train <- df %>% slice(inds) # Use the 80% to get the training data
  test <- df %>% slice(-inds) # Drop the 80% to get the test data
  
  m <- lm(Rushing.Yards ~ Rushing.Attempts + Rushing.Success.Rate, data = train) # Train the model on the train data
  
  test$errors <- predict(m, newdata = test) # Generate predicted values from the model
  
  e <- test$Rushing.Yards - test$errors # Calculate the errors as the true Y minus the predicted Y
  se <- e^2 # Square the errors
  mse <- mean(se) # Take the mean of the squared errors
  rmse <- sqrt(mse) # Take the square root of the mean of the squared errors
  cvRes <- c(cvRes, rmse) # Append the rmse to the cvRes object
} 

mean(cvRes)
```
